#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = []

#Cell
from .imports import *
from .torch_imports import *
from .torch_core import *

#Cell
if torch.cuda.is_available():
    if torch.cuda.current_device()==0:
        torch.cuda.set_device(int(os.environ.get('DEFAULT_GPU') or 0))
    torch.backends.cudnn.benchmark = True